baseurl = "http://blog.shamm.as"
languageCode = "en-us"
Title = "George Shammas"
# Copyright notice. This is displayer in the footer.
# copyright = "All rights reserved"
theme = "ananke"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "georgyo"
  facebook = "shammas"
  instagram = "ge0rgy0"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "georgyo"
  gitlab = "georgyo"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  flickr = "georgyo"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  linkedin = "georgeshammas"
  # Disqus shortname
  disqus = "shammas"
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    identifier = "theme"
    name = "Theme"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = true

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
